### PR TITLE
Added option to set names in script 

### PR DESCRIPTION
**Pull request by tonyeung**
## Describe your Pull Request
Added option to set names in script.
Also added logging to inform user if their email is not set

Fixes # (issue)
https://github.com/whiteducksoftware/terraform-scaffold-for-azure/issues/8

Please select relevant options:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have checked my code and corrected any misspellings

Reviewer: @nmeisenzahl

### CODE REVIEW

**Comment by nmeisenzahl** [comment]
@tonyeung thank you for your contribution. Do you mind moving your added variable checks (except the existing; those are not set in the .env file) below the .env source section to not break the sourcing option.

**Comment by tonyeung** [comment]
@nmeisenzahl does this work? my shell skills are novice at best, so not sure if I delivered the ask.

**Comment by nmeisenzahl** [comment]
Hi @tonyeung I just did a full review of your contribution. I like the idea of adding further checks in case the .env file wasn't sourced or does not contain the required variables. 

To be honest I don't see the added value of defining the values in multiple places in the script instead of the .env file. Can you please elaborate on this? Can you please describe your use case in more detail?

**Comment by tonyeung** [comment]
I ran the script as a test to see what it would create in a temporary VM. rather than messing with environmental variables I could do all my testing in the script itself. If you don't think its necessary that's fine. Like I said, I've already done my testing.

**Pull request closed without merging**
